# Generated by Django 3.2.7 on 2021-10-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charity_id', models.IntegerField()),
                ('charity_name', models.CharField(max_length=30)),
                ('charity_address', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
                ('charity_bio', models.TextField(max_length=255)),
                ('trustdeed', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
