# Generated by Django 3.2.7 on 2021-10-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
