# Generated by Django 3.2 on 2021-10-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.IntegerField()),
                ('donorname', models.CharField(max_length=30)),
                ('emailaddress', models.CharField(max_length=30)),
                ('phonenumber', models.IntegerField(max_length=10)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
