# Generated by Django 3.2 on 2021-10-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donorsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
