# Generated by Django 3.2.8 on 2021-10-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donorsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='donor_name',
            field=models.CharField(default='no name', max_length=30),
        ),
        migrations.AlterField(
            model_name='donors',
            name='email_address',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='donors',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
