# Generated by Django 3.2 on 2021-10-07 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donorsapp', '0002_alter_donors_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donors',
            name='password',
        ),
    ]
