# Generated by Django 3.2 on 2021-10-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donorsapp', '0003_remove_donors_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donors',
            name='donor_id',
        ),
    ]
